name: Docker build and deploy
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - 'master'

jobs:
  docker-build:
    name: "Build and push docker"
    runs-on: [ ubuntu-latest ]
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
    steps:
      - name: Login to docker.io
        run: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $DOCKER_LOGIN/$DOCKER_NAME:latest .
      - name: Push image to docker.io
        run: docker push $DOCKER_LOGIN/$DOCKER_NAME:latest
  deploy:
    name: "Deploy to server"
    runs-on: [ ubuntu-latest ]
    needs: [docker-build]
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PWD }}
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      ENVFILE: ${{ secrets.ENVFILE }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - uses: actions/checkout@master

      - name: Create env file
        run: |
          echo -e $ENVFILE >> .env
          echo DOCKER_LOGIN=$DOCKER_LOGIN >> .env
          echo DOCKER_PASSWORD=$DOCKER_PASSWORD >> .env
          echo DOCKER_NAME=$DOCKER_NAME >> .env
          echo AWS_BUCKET_NAME=$AWS_BUCKET_NAME >> .env
          echo AWS_S3_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY_ID >> .env
          echo AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY >> .env

      - name: Copy files to vm
        run: |
          scp docker-compose.yaml staging:~/docker-compose.yaml
          scp .env staging:~/.env

      - name: Run deploy.sh
        run: |
          envsubst < deploy.sh | ssh staging sh